backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "/site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "qualifier"
    label: "Qualifier"
    folder: "site/content/qualifier"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: string, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}
  - name: "mean"
    label: "Mean Stack"
    folder: "site/content/mean"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: string, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}
  - name: "ionic"
    label: "Ionic"
    folder: "site/content/ionic"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: string, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}
  - name: "group"
    label: "Group Project"
    folder: "site/content/group"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: string, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}
  - name: "pages"
    label: "Pages"
    folder: "site/content/"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Weight, name: weight, widget: string, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}