backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: master # Branch to update (optional; defaults to master)

slug:
  encoding: "ascii"
  clean_accents: true

publish_mode: editorial_workflow
media_folder: "/site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - label: "Home"
    name: "home"
    extension: "md"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Weight, name: weight, widget: number, required: false}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Content, name: body, widget: markdown}
  - label: "Pages"
    name: "pages"
    extension: "md"
    folder: "site/content/"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Weight, name: weight, widget: number, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Content, name: body, widget: markdown}
  - label: "Qualifier"
    name: "qualifier"
    extension: "md"
    folder: "site/content/qualifier"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: number, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Content, name: body, widget: markdown}
  - label: "MEAN Stack"
    name: "mean"
    extension: "md"
    folder: "site/content/mean"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: number, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Content, name: body, widget: markdown}
  - label: "Ionic"
    name: "ionic"
    extension: "md"
    folder: "site/content/ionic"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: number, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Content, name: body, widget: markdown}
  - name: "group"
    label: "Group"
    extension: "md"
    folder: "site/content/group"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Chapter, name: chapter, widget: boolean, required: false}
      - {label: Weight, name: weight, widget: number, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Content, name: body, widget: markdown}
